name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  typecheck_lint_format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Enable Corepack
        run: corepack enable

      - name: Prepare pnpm (Corepack)
        run: corepack prepare pnpm@9.0.0 --activate

      - name: Debug pnpm version
        run: pnpm -v

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint (workspace)
        run: pnpm -r --if-present lint

      - name: Format check (Prettier)
        run: pnpm run format:check

      - name: Typecheck
        run: pnpm -r --parallel typecheck
